@port = 3000

###
### POST Request for a contact 
## Expected result is ........
# @name postWeather

POST http://localhost:{{port}}/api/v1/weather HTTP/1.1
content-type: application/json

{ "Location" : "Ireland"}

###
 @newObjectID = {{postWeather.response.headers.Location}}

 GET http://localhost:{{port}}/api/v1/weather/{{newObjectID}} HTTP/1.1
