@port = 3000

###
### POST Request for a contact 
## Expected result is ........
# @name postWeather

POST http://localhost:{{port}}/api/v1/weather HTTP/1.1
content-type: application/json

{ "location" : "Jamaica",
    "weather" : "Humid",
    "temperature": "36"}

###
//Post that fails

POST http://localhost:{{port}}/api/v1/weather HTTP/1.1
content-type: application/json

{ "location" : "Sc",
    "weather" : "Rain",
    "chance of Rain" : true,
    "Temperature": 1001}

###
@newObjectID = {{postWeather.response.headers.location}}

GET http://localhost:{{port}}/api/v1/weather?location=England

###
GET http://localhost:{{port}}/api/v1/weather?id=65341604be12c2f24f20657e

###
//invalid id
GET http://localhost:{{port}}/api/v1/weather?id=65340604be12c2f24f20657e

###

//Put fail, invalid data
PUT http://localhost:{{port}}/api/v1/weather/{{newObjectID}} HTTP/1.1
content-type: application/json

{ "location" : "England",
"chanceRain" : "pink"
}

###
//Delete which fails

DELETE http://localhost:{{port}}/api/v1/weather?id=653429e0deecaedf80d85c41